name: Build Test & Deploy
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Fetching ParteiDuell Data"
        uses: textbook/git-checkout-submodule-action@master
      - name: Install dependencies
        run: pub get
      - name: Building source
        run: dart2native bin/main.dart -o parteiduell_backend-linux-x64-release
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: parteiduell_backend-linux-x64-release
  deploy:
    name: Deploy to production
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Fetching ParteiDuell Data"
        uses: textbook/git-checkout-submodule-action@master      
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy build
        env:
          SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
          rsync -az --progress -e ssh ./build/parteiduell_backend-linux-x64-release data root@parteiduell.de:/var/www/api.parteiduell.de/production/build --delete
          ssh root@parteiduell.de chmod a+x /var/www/api.parteiduell.de/production/build/parteiduell_backend-linux-x64-release
          ssh root@parteiduell.de sudo systemctl restart parteiduell_backend
