name: Build Test & Deploy
on:
  release:
    types: [created]
    branches: main

jobs:
  build:
    env:
      RELEASE_VERSION: ${{github.event.release.tag_name}}
      RELEASE_FILE: parteiduell_backend-${{github.event.release.tag_name}}
    name: Build
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Preparing the Build
        run: sh ./injectVersion.sh ${RELEASE_VERSION}
      - name: Building source
        run: dart2native bin/main.dart -o ${RELEASE_FILE}
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.RELEASE_FILE}}
          path: ${{env.RELEASE_FILE}}
      - name: Package Release
        run: tar -zcf ${RELEASE_FILE}.tar.gz ${RELEASE_FILE} README.md
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          asset_path: ${{env.RELEASE_FILE}}.tar.gz
          upload_url: ${{github.event.release.upload_url}}
          asset_name: ${{env.RELEASE_FILE}}.tar.gz
          asset_content_type: application/octet-stream
  deploy:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy build
        env:
          SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
          rsync -az --progress -e ssh ./build/${RELEASE_FILE} root@parteiduell.de:/var/www/api.parteiduell.de/production/build            
      - name: Preparing restart
        run: |
          ssh root@parteiduell.de rm /var/www/api.parteiduell.de/production/build/parteiduell_backend-linux-x64-release
          ssh root@parteiduell.de cp /var/www/api.parteiduell.de/production/build/${RELEASE_FILE} /var/www/api.parteiduell.de/production/build/parteiduell_backend-linux-x64-release
          ssh root@parteiduell.de rm /var/www/api.parteiduell.de/production/build/${RELEASE_FILE}
      - name: Restart the backend service on the server
        run: |
          ssh root@parteiduell.de chmod a+x /var/www/api.parteiduell.de/production/build/parteiduell_backend-linux-x64-release
          ssh root@parteiduell.de sudo systemctl restart parteiduell_backend
